name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start server
        run: |
          nohup npm start >/dev/null 2>&1 &
          for i in {1..60}; do
            if curl -fsS http://localhost:3000/api/health >/dev/null; then echo "server up"; break; fi
            sleep 1
          done
      - name: E2E tests
        run: npm run e2e
